const ProjectsData = [
  {
    id: 0,
    path: "instagram",
    title: "Instagram",
    description: "Copy of Instagram page",
    link: "https://instagram-dani.vercel.app/",
    img: "insta.png",
    image: "insta.gif",
    imageMobile: "mobileInsta.gif",
  },
  {
    id: 1,
    path: "badges",
    title: "Badges",
    description: "CRUD application, to create, edit, modify and delete users.",
    link: "https://badges-daniel-vasquez.vercel.app/",
    img: "badges.png",
    image: "badges.gif",
    imageMobile: "mobileBadges.gif",
  },
  {
    id: 2,
    path: "platzi-video",
    title: "Platzi video",
    description: "Website layout. Using only HTML and CSS",
    link: "https://daniel-vasquez.github.io/platzi-video/",
    img: "platziVideo.png",
    image: "platziVideo.gif",
    imageMobile: "mobilePlatziVideo.gif",
  },
  {
    id: 3,
    path: "maquetacion",
    title: "Maquetación",
    description: "Web Components",
    link: "https://daniel-vasquez.github.io/maquetacion/",
    img: "maquetacion.png",
    image: "maquetacion.gif",
    imageMobile: "mobileMaquetacion.gif",
  },
  {
    id: 4,
    path: "responsive-design",
    title: "Responsive design",
    description: "Responsive first project",
    link: "https://daniel-vasquez.github.io/responsive-design/",
    img: "responsiveDesign.png",
    image: "responsiveDesign.gif",
    imageMobile: "mobileResponsiDesign.gif",
  },
];

export default ProjectsData;
