const ProjectsData = [
  {
    id: 0,
    path: "instagram",
    title: "Instagram",
    description: "Copia de la página de Instagram",
    link: "https://instagram-dani.vercel.app/",
    img: "insta.png",
    gif: "insta.gif",
    imageMobile: "mobileInsta.gif",
    codigo: "https://github.com/Daniel-Vasquez/instagram",
  },
  {
    id: 1,
    path: "badges",
    title: "Badges",
    description:
      "Aplicación CRUD, para crear, editar, modificar y eliminar usuarios",
    link: "https://badges-daniel-vasquez.vercel.app/",
    img: "badges.png",
    gif: "badges.gif",
    imageMobile: "mobileBadges.gif",
    codigo: "https://github.com/Daniel-Vasquez/badges",
  },
  {
    id: 2,
    path: "platzi-video",
    title: "Platzi video",
    description: "Website layout. Usando solo HTML y CSS",
    link: "https://daniel-vasquez.github.io/platzi-video/",
    img: "platziVideo.png",
    gif: "platziVideo.gif",
    imageMobile: "mobilePlatziVideo.gif",
    codigo: "https://github.com/Daniel-Vasquez/platzi-video",
  },
  {
    id: 3,
    path: "maquetacion",
    title: "Maquetación",
    description: "Web Components",
    link: "https://daniel-vasquez.github.io/maquetacion/",
    img: "maquetacion.png",
    gif: "maquetacion.gif",
    imageMobile: "mobileMaquetacion.gif",
    codigo: "https://github.com/Daniel-Vasquez/maquetacion",
  },
  {
    id: 4,
    path: "responsive-design",
    title: "Responsive design",
    description: "Primer proyecto responsive",
    link: "https://daniel-vasquez.github.io/responsive-design/",
    img: "responsiveDesign.png",
    gif: "responsiveDesign.gif",
    imageMobile: "mobileResponsiDesign.gif",
    codigo: "https://github.com/Daniel-Vasquez/responsive-design",
  },
];

export default ProjectsData;
